### ISSUE TITLE
iOS 8?

### ISSUE THREAD

**Issue by tateu** [insanj/Orangered#7]
How's the update for iOS 8 coming along? I see you made some changes back in November.  I've added a few more and have a partially working build running on my 5s and iPad 4, iOS 8.1.2.

https://github.com/tateu/Orangered

**Comment by insanj** [comment]
Thanks for checking in! I passed off the responsibility to @codyd51, but he's been incredibly busy with family and other projects. If you have any additions or fixes to introduce—the primary requirement being updates to our usage of BulletinBoard to match iOS 8's changes—please make a pull request as soon as possible. I'm always open to contribution, and would love to see Orangered back in people's hands. It's only due to time constraints that this hasn't already been done (also, @kirb's hbangcommon update to resolve preference synchronization issues).

**Comment by tateu** [comment]
What needs to be done with BulletinBoard? I switched it back to BBDataProviderAddBulletin and it seems to be working fine. The main thing that isn't working for me, is the RingTone preference page. It crashes the Preference app.

**Comment by insanj** [comment]
Now that the [Cephei](https://github.com/hbang/libcephei) update has been completed, and I've officially given up hope for @codyd51, I'll start work on this today and the rest of this week. Sorry about the delay!

**Comment by tateu** [comment]
Sounds good. Thanks. I've never been able to figure out the RingtoneController issue but I wrote my own ring tone interface. It's not amazing but, if you can't figure anything else out, it might be worth taking a look at. I haven't added that code to my github page but I can send you a deb of my latest build.

**Comment by codyd51** [comment]
(Just as a side note, I've been working on Velox 2 for about 3 months now. I haven't worked on anything else besides this, but release is in sight. I'm anticipating somewhere a little under two weeks @insanj :)

**Comment by insanj** [comment]
Functional as of fc23dba91ea97733c01fa4d8755918a875e5b626, give it a whirl! Going to play around with it for another day or two before releasing, just to make sure the bugs and such are caught.

**Comment by tateu** [comment]
Two small things:
1) I added the new Alien Blue HD bundle identifier.
2) [orangeredPreferences floatForKey:@"refreshInterval" default:60.0] fails for me (always returns 0) and it was missing "* intervalUnit". Cephei floatForKey checks "isKindOfClass:NSNumber.class" but refreshInterval is written to my preference plist file as a string, so the function returns 0. I reverted to grabbing the value as an NSSting and converting it with floatValue.

https://github.com/tateu/Orangered/commit/ce514ae617ff666a0a3086f8bcf8f971bfc550ad

I'm also not super thrilled with the Ring Tone panel. It only shows alertTones. I created one for "Mail Labeler" that shows three different sections, each sorted alphabetically, and it plays the tone when you tap on it. The 1st section contains installedTones, which are any tones the user installed via iTunes (and I think via ToneEnabler, too).  The 2nd section contains alertTones. The 3rd sections contains all m4r ringtones in /Library/Ringtones. I'll work on integrating it with the latest Orangered changes, maybe later today or tomorrow night, so you can see it.

**Comment by tateu** [comment]
And PlatypusW and I had a discussion on Reddit, https://www.reddit.com/r/jailbreakdevelopers/comments/2u2r2g/activator_scheduling_anyone_know_how_its/, about PCPersistentTimer. It turns out that PCPersistentTimer has a property, _earlyFireTime, which, as the name implies, causes it to sometimes fire early. He found PCSimpleTimer, which does not appear to have this issue. We have both switched our projects over to using it with no known ill side effects so far.

https://github.com/tateu/Orangered/commit/2325ee802d49f161234e032f004ff18c727df95c

**Comment by tateu** [comment]
I fixed a crash on the iPad when pressing Return on the keyboard while editing the Refresh Interval: https://github.com/tateu/Orangered/commit/34497095d4ab9c2b5f223547fccfbb243faaefeb

and added my custom Ring Tone panel: https://github.com/tateu/Orangered/commit/59042482bc16b2cf4906fb14a334c76bf37170b1

**Comment by tateu** [comment]
And you got rid of the LastBulletin check "Not publishing duplicate bulletin request" so it will continually re-notify me every 15 minutes about the same unread message. Personally, I don't want it to do that but some people might want it that way. Maybe add it as an option?

**Comment by insanj** [comment]
Okay. How goes the integration of that fancy tone panel?

**Comment by tateu** [comment]
Done about 18 hours ago...and it's not that fancy...but it might be worth a look...https://github.com/tateu/Orangered/commit/59042482bc16b2cf4906fb14a334c76bf37170b1

**Comment by insanj** [comment]
Fantastic, I'll merge the changes and ship soon.

**Comment by tateu** [comment]
And an option to disable repeat notifications: https://github.com/tateu/Orangered/commit/38ac19bd73eba573f9c7e0d2ecfbe2c8fb70a177

**Comment by insanj** [comment]
Do you have an email address I can contact you with to discuss moving forward with proper attribution?

**Comment by tateu** [comment]
tateu@tateu.net
